package se.yrgo.up22.group1.coach;

public class Coach {

    private final String name;

    public Coach(String name) {
        this.name = name;
    }


    //Stub generated by Magnus
    @Override
    public String toString() {
        return " " + name;
    }

    //Stub generated by Magnus
    public String getName() {
        return name;
    }
}
